import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Reveal from '@/components/Reveal';
import CountUp from '@/components/CountUp';

const STATS = [
  { value: 60, suffix: 's', label: 'average analysis' },
  { value: 12, suffix: '+', label: 'sectors' },
  { raw: 'Free', label: 'to start' },
];

export default function LandingPage() {
  return (
    <>
      <Navbar />

      <main>
        {/* Hero */}
        <section className="relative overflow-hidden">
          <div
            className="pointer-events-none absolute inset-0 -z-10 opacity-60"
            style={{
              background:
                'radial-gradient(600px circle at 50% -10%, rgba(0,208,132,0.16), transparent 60%)',
            }}
          />
          <div className="mx-auto max-w-6xl px-5 pb-16 pt-20 text-center sm:pt-28">
            {/* Animated pulsing badge — reveals first (0ms) */}
            <div
              className="reveal-load mx-auto mb-8 inline-flex items-center gap-2 rounded-full border border-line bg-surface px-4 py-1.5 text-sm text-ink-muted"
              style={{ animationDelay: '0ms' }}
            >
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-pulseRing rounded-full bg-green" />
                <span className="relative inline-flex h-2 w-2 animate-pulseDot rounded-full bg-green" />
              </span>
              AI-powered market research, live
            </div>

            {/* Headline — slides up (200ms) */}
            <h1
              className="reveal-load font-display text-5xl font-extrabold leading-[1.05] tracking-tight sm:text-7xl"
              style={{ animationDelay: '200ms' }}
            >
              Markets analyzed.
              <br />
              <span className="text-green">In seconds.</span>
            </h1>

            {/* Subtitle (400ms) */}
            <p
              className="reveal-load mx-auto mt-6 max-w-xl text-lg text-ink-muted"
              style={{ animationDelay: '400ms' }}
            >
              Pick a sector, set your filters, and get a structured, source-backed
              research report — macro context, featured companies, and upcoming
              catalysts — generated by AI in about a minute.
            </p>

            {/* CTAs (600ms) */}
            <div
              className="reveal-load mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"
              style={{ animationDelay: '600ms' }}
            >
              <Link href="/research" className="btn-green px-6 py-3 text-base">
                Start my first research →
              </Link>
              <Link href="#preview" className="btn-ghost px-6 py-3 text-base">
                See an example
              </Link>
            </div>

            {/* Stats row — numbers count up when in view */}
            <div className="mx-auto mt-16 grid max-w-2xl grid-cols-3 gap-4">
              {STATS.map((s) => (
                <div key={s.label} className="card px-4 py-6">
                  <div className="font-display text-3xl font-bold text-green sm:text-4xl">
                    {s.raw ? s.raw : <CountUp value={s.value} suffix={s.suffix} />}
                  </div>
                  <div className="mt-1 text-sm text-ink-muted">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Preview card — slides up + fades in when in view */}
        <Reveal as="section" y={30} className="mx-auto block max-w-4xl px-5 pb-24">
          <div id="preview" className="card overflow-hidden shadow-2xl">
            {/* Browser chrome */}
            <div className="flex items-center gap-2 border-b border-line bg-surface2 px-4 py-3">
              <span className="h-3 w-3 rounded-full bg-[#ff5f57]" />
              <span className="h-3 w-3 rounded-full bg-[#febc2e]" />
              <span className="h-3 w-3 rounded-full bg-[#28c840]" />
              <div className="ml-4 flex-1">
                <div className="mx-auto max-w-sm rounded-md border border-line bg-bg px-3 py-1 text-center text-xs text-ink-muted">
                  alphalens.app/result/ai-large-cap
                </div>
              </div>
            </div>

            {/* Body */}
            <div className="p-6 sm:p-8">
              <div className="mb-5 flex flex-wrap gap-2">
                {['AI / Software', 'Large Cap $10B+', 'Mid-term', 'United States'].map((c) => (
                  <span key={c} className="chip chip-active px-3 py-1 text-xs">
                    {c}
                  </span>
                ))}
              </div>

              <div className="mb-6 rounded-xl border-l-2 border-green bg-surface2 p-4">
                <div className="skeleton mb-2 h-3 w-3/4" />
                <div className="skeleton mb-2 h-3 w-full" />
                <div className="skeleton h-3 w-2/3" />
              </div>

              <div className="grid gap-3 sm:grid-cols-2">
                {[0, 1, 2, 3].map((i) => (
                  <div key={i} className="card flex items-center gap-3 p-4">
                    <div className="skeleton h-10 w-10 rounded-lg" />
                    <div className="flex-1">
                      <div className="skeleton mb-2 h-3 w-1/2" />
                      <div className="skeleton h-3 w-3/4" />
                    </div>
                    <div className="skeleton h-6 w-12 rounded-full" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Reveal>
      </main>

      <Footer />
    </>
  );
}
